/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:450f225e-5616-4541-86f6-05bc41335145",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_XEtO0dd0l",
    "aws_user_pools_web_client_id": "2stkj9cjecat17nmavid58ftm",
    "oauth": {}
};


export default awsmobile;
